print("1. mode")
operation = input("choose number:")
if operation =="1":
   print("start")
   l = input("put the value of l:")
   f1= input("put the value of f1:")
   f2= input("put the value of f2:")
   f0 = input("put the value of f0 :")
   h = input("put the value of h : ")
   print("f1 - f0")
   f = int(f1) - int(f0)
   print(f)
   f2 = int(2)* int(f1) - int(f0) - int(f2)
   print("2f1 - f0 - f2")
   print(f2)
   print("F1- f0 × h")
   ff2 = int(f) * int(h)
   print(ff2)
   print("2f1-f0-f2")
   f22 = int(f2) / int(ff2)
   print(f22)
   ff3 = int(f22)+ int(l)
   print("so,the last step : additional of l by the solving equation")
   print(ff3) 
   print("programe finished")
