print("1. mode")
operation = input("choose number:")
if operation =="1":
   print("start")
   l = input("put the value of l:")
   f1= input("put the value of f1:")
   f2= input("put the value of f2:")
   f0 = input("put the value of f0 :")
   h = input("put the value of h : ")
   print("f1 - f0")
   print(f)
   f2 = int(2)* int(f1) - int(f0) - int(f2)
   print("2f1 - f0 - f2")
   print(f2)
   ff2 = int(f) * int(h)
   print("first we have to do multiplication of h ÷ f1 - f0")
   ff3 = int(ff2)+ int(l)
   print("so,the last step : additional of l by the solving equation")
   l2 = int(ff3) + int(l)
   print(l2)
   print("programe finished")
